#############################################################################
# Makefile for building: ZBY_MQQ
# Generated by qmake (3.1) (Qt 5.12.9)
# Project:  ZBY_MQQ.pro
# Template: subdirs
# Command: C:\Qt\Qt5.12.9\5.12.9\mingw73_64\bin\qmake.exe -o Makefile ZBY_MQQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = C:\Qt\Qt5.12.9\5.12.9\mingw73_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\Qt5.12.9\5.12.9\mingw73_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\Qt5.12.9\5.12.9\mingw73_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-DataInterPort \
		sub-DataInterSerailPort \
		sub-DataInterModbus \
		sub-DataInterRabbitMQ \
		sub-DataInterTcp \
		sub-DataInterchange \
		sub-LogController-LogController-pro \
		sub-WeightModbus \
		sub-ZBY_MQ-ZBY_MQ-pro


sub-DataInterPort-qmake_all:  FORCE
	@if not exist DataInterPort\ mkdir DataInterPort\ & if not exist DataInterPort\ exit 1
	cd DataInterPort\ && $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterPort\DataInterPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd DataInterPort\ && $(MAKE) -f Makefile qmake_all
sub-DataInterPort: FORCE
	@if not exist DataInterPort\ mkdir DataInterPort\ & if not exist DataInterPort\ exit 1
	cd DataInterPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterPort\DataInterPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-DataInterPort-make_first: FORCE
	@if not exist DataInterPort\ mkdir DataInterPort\ & if not exist DataInterPort\ exit 1
	cd DataInterPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterPort\DataInterPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-DataInterPort-all: FORCE
	@if not exist DataInterPort\ mkdir DataInterPort\ & if not exist DataInterPort\ exit 1
	cd DataInterPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterPort\DataInterPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-DataInterPort-clean: FORCE
	@if not exist DataInterPort\ mkdir DataInterPort\ & if not exist DataInterPort\ exit 1
	cd DataInterPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterPort\DataInterPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-DataInterPort-distclean: FORCE
	@if not exist DataInterPort\ mkdir DataInterPort\ & if not exist DataInterPort\ exit 1
	cd DataInterPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterPort\DataInterPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-DataInterPort-install_subtargets: FORCE
	@if not exist DataInterPort\ mkdir DataInterPort\ & if not exist DataInterPort\ exit 1
	cd DataInterPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterPort\DataInterPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-DataInterPort-uninstall_subtargets: FORCE
	@if not exist DataInterPort\ mkdir DataInterPort\ & if not exist DataInterPort\ exit 1
	cd DataInterPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterPort\DataInterPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-DataInterSerailPort-qmake_all:  FORCE
	@if not exist DataInterSerailPort\ mkdir DataInterSerailPort\ & if not exist DataInterSerailPort\ exit 1
	cd DataInterSerailPort\ && $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterSerailPort\DataInterSerailPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd DataInterSerailPort\ && $(MAKE) -f Makefile qmake_all
sub-DataInterSerailPort: FORCE
	@if not exist DataInterSerailPort\ mkdir DataInterSerailPort\ & if not exist DataInterSerailPort\ exit 1
	cd DataInterSerailPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterSerailPort\DataInterSerailPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-DataInterSerailPort-make_first: FORCE
	@if not exist DataInterSerailPort\ mkdir DataInterSerailPort\ & if not exist DataInterSerailPort\ exit 1
	cd DataInterSerailPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterSerailPort\DataInterSerailPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-DataInterSerailPort-all: FORCE
	@if not exist DataInterSerailPort\ mkdir DataInterSerailPort\ & if not exist DataInterSerailPort\ exit 1
	cd DataInterSerailPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterSerailPort\DataInterSerailPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-DataInterSerailPort-clean: FORCE
	@if not exist DataInterSerailPort\ mkdir DataInterSerailPort\ & if not exist DataInterSerailPort\ exit 1
	cd DataInterSerailPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterSerailPort\DataInterSerailPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-DataInterSerailPort-distclean: FORCE
	@if not exist DataInterSerailPort\ mkdir DataInterSerailPort\ & if not exist DataInterSerailPort\ exit 1
	cd DataInterSerailPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterSerailPort\DataInterSerailPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-DataInterSerailPort-install_subtargets: FORCE
	@if not exist DataInterSerailPort\ mkdir DataInterSerailPort\ & if not exist DataInterSerailPort\ exit 1
	cd DataInterSerailPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterSerailPort\DataInterSerailPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-DataInterSerailPort-uninstall_subtargets: FORCE
	@if not exist DataInterSerailPort\ mkdir DataInterSerailPort\ & if not exist DataInterSerailPort\ exit 1
	cd DataInterSerailPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterSerailPort\DataInterSerailPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-DataInterModbus-qmake_all:  FORCE
	@if not exist DataInterModbus\ mkdir DataInterModbus\ & if not exist DataInterModbus\ exit 1
	cd DataInterModbus\ && $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterModbus\DataInterModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd DataInterModbus\ && $(MAKE) -f Makefile qmake_all
sub-DataInterModbus: FORCE
	@if not exist DataInterModbus\ mkdir DataInterModbus\ & if not exist DataInterModbus\ exit 1
	cd DataInterModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterModbus\DataInterModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-DataInterModbus-make_first: FORCE
	@if not exist DataInterModbus\ mkdir DataInterModbus\ & if not exist DataInterModbus\ exit 1
	cd DataInterModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterModbus\DataInterModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-DataInterModbus-all: FORCE
	@if not exist DataInterModbus\ mkdir DataInterModbus\ & if not exist DataInterModbus\ exit 1
	cd DataInterModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterModbus\DataInterModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-DataInterModbus-clean: FORCE
	@if not exist DataInterModbus\ mkdir DataInterModbus\ & if not exist DataInterModbus\ exit 1
	cd DataInterModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterModbus\DataInterModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-DataInterModbus-distclean: FORCE
	@if not exist DataInterModbus\ mkdir DataInterModbus\ & if not exist DataInterModbus\ exit 1
	cd DataInterModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterModbus\DataInterModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-DataInterModbus-install_subtargets: FORCE
	@if not exist DataInterModbus\ mkdir DataInterModbus\ & if not exist DataInterModbus\ exit 1
	cd DataInterModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterModbus\DataInterModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-DataInterModbus-uninstall_subtargets: FORCE
	@if not exist DataInterModbus\ mkdir DataInterModbus\ & if not exist DataInterModbus\ exit 1
	cd DataInterModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterModbus\DataInterModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-DataInterRabbitMQ-qmake_all:  FORCE
	@if not exist DataInterRabbitMQ\ mkdir DataInterRabbitMQ\ & if not exist DataInterRabbitMQ\ exit 1
	cd DataInterRabbitMQ\ && $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterRabbitMQ\DataInterRabbitMQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd DataInterRabbitMQ\ && $(MAKE) -f Makefile qmake_all
sub-DataInterRabbitMQ: FORCE
	@if not exist DataInterRabbitMQ\ mkdir DataInterRabbitMQ\ & if not exist DataInterRabbitMQ\ exit 1
	cd DataInterRabbitMQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterRabbitMQ\DataInterRabbitMQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-DataInterRabbitMQ-make_first: FORCE
	@if not exist DataInterRabbitMQ\ mkdir DataInterRabbitMQ\ & if not exist DataInterRabbitMQ\ exit 1
	cd DataInterRabbitMQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterRabbitMQ\DataInterRabbitMQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-DataInterRabbitMQ-all: FORCE
	@if not exist DataInterRabbitMQ\ mkdir DataInterRabbitMQ\ & if not exist DataInterRabbitMQ\ exit 1
	cd DataInterRabbitMQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterRabbitMQ\DataInterRabbitMQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-DataInterRabbitMQ-clean: FORCE
	@if not exist DataInterRabbitMQ\ mkdir DataInterRabbitMQ\ & if not exist DataInterRabbitMQ\ exit 1
	cd DataInterRabbitMQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterRabbitMQ\DataInterRabbitMQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-DataInterRabbitMQ-distclean: FORCE
	@if not exist DataInterRabbitMQ\ mkdir DataInterRabbitMQ\ & if not exist DataInterRabbitMQ\ exit 1
	cd DataInterRabbitMQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterRabbitMQ\DataInterRabbitMQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-DataInterRabbitMQ-install_subtargets: FORCE
	@if not exist DataInterRabbitMQ\ mkdir DataInterRabbitMQ\ & if not exist DataInterRabbitMQ\ exit 1
	cd DataInterRabbitMQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterRabbitMQ\DataInterRabbitMQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-DataInterRabbitMQ-uninstall_subtargets: FORCE
	@if not exist DataInterRabbitMQ\ mkdir DataInterRabbitMQ\ & if not exist DataInterRabbitMQ\ exit 1
	cd DataInterRabbitMQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterRabbitMQ\DataInterRabbitMQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-DataInterTcp-qmake_all:  FORCE
	@if not exist DataInterTcp\ mkdir DataInterTcp\ & if not exist DataInterTcp\ exit 1
	cd DataInterTcp\ && $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterTcp\DataInterTcp.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd DataInterTcp\ && $(MAKE) -f Makefile qmake_all
sub-DataInterTcp: FORCE
	@if not exist DataInterTcp\ mkdir DataInterTcp\ & if not exist DataInterTcp\ exit 1
	cd DataInterTcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterTcp\DataInterTcp.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-DataInterTcp-make_first: FORCE
	@if not exist DataInterTcp\ mkdir DataInterTcp\ & if not exist DataInterTcp\ exit 1
	cd DataInterTcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterTcp\DataInterTcp.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-DataInterTcp-all: FORCE
	@if not exist DataInterTcp\ mkdir DataInterTcp\ & if not exist DataInterTcp\ exit 1
	cd DataInterTcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterTcp\DataInterTcp.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-DataInterTcp-clean: FORCE
	@if not exist DataInterTcp\ mkdir DataInterTcp\ & if not exist DataInterTcp\ exit 1
	cd DataInterTcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterTcp\DataInterTcp.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-DataInterTcp-distclean: FORCE
	@if not exist DataInterTcp\ mkdir DataInterTcp\ & if not exist DataInterTcp\ exit 1
	cd DataInterTcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterTcp\DataInterTcp.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-DataInterTcp-install_subtargets: FORCE
	@if not exist DataInterTcp\ mkdir DataInterTcp\ & if not exist DataInterTcp\ exit 1
	cd DataInterTcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterTcp\DataInterTcp.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-DataInterTcp-uninstall_subtargets: FORCE
	@if not exist DataInterTcp\ mkdir DataInterTcp\ & if not exist DataInterTcp\ exit 1
	cd DataInterTcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterTcp\DataInterTcp.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-DataInterchange-qmake_all:  FORCE
	@if not exist DataInterchange\ mkdir DataInterchange\ & if not exist DataInterchange\ exit 1
	cd DataInterchange\ && $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterchange\DataInterchange.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd DataInterchange\ && $(MAKE) -f Makefile qmake_all
sub-DataInterchange: FORCE
	@if not exist DataInterchange\ mkdir DataInterchange\ & if not exist DataInterchange\ exit 1
	cd DataInterchange\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterchange\DataInterchange.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-DataInterchange-make_first: FORCE
	@if not exist DataInterchange\ mkdir DataInterchange\ & if not exist DataInterchange\ exit 1
	cd DataInterchange\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterchange\DataInterchange.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-DataInterchange-all: FORCE
	@if not exist DataInterchange\ mkdir DataInterchange\ & if not exist DataInterchange\ exit 1
	cd DataInterchange\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterchange\DataInterchange.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-DataInterchange-clean: FORCE
	@if not exist DataInterchange\ mkdir DataInterchange\ & if not exist DataInterchange\ exit 1
	cd DataInterchange\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterchange\DataInterchange.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-DataInterchange-distclean: FORCE
	@if not exist DataInterchange\ mkdir DataInterchange\ & if not exist DataInterchange\ exit 1
	cd DataInterchange\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterchange\DataInterchange.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-DataInterchange-install_subtargets: FORCE
	@if not exist DataInterchange\ mkdir DataInterchange\ & if not exist DataInterchange\ exit 1
	cd DataInterchange\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterchange\DataInterchange.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-DataInterchange-uninstall_subtargets: FORCE
	@if not exist DataInterchange\ mkdir DataInterchange\ & if not exist DataInterchange\ exit 1
	cd DataInterchange\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterchange\DataInterchange.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-LogController-LogController-pro-qmake_all:  FORCE
	@if not exist LogController\ mkdir LogController\ & if not exist LogController\ exit 1
	cd LogController\ && $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\LogController\LogController.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd LogController\ && $(MAKE) -f Makefile qmake_all
sub-LogController-LogController-pro: FORCE
	@if not exist LogController\ mkdir LogController\ & if not exist LogController\ exit 1
	cd LogController\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\LogController\LogController.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-LogController-LogController-pro-make_first: FORCE
	@if not exist LogController\ mkdir LogController\ & if not exist LogController\ exit 1
	cd LogController\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\LogController\LogController.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-LogController-LogController-pro-all: FORCE
	@if not exist LogController\ mkdir LogController\ & if not exist LogController\ exit 1
	cd LogController\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\LogController\LogController.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-LogController-LogController-pro-clean: FORCE
	@if not exist LogController\ mkdir LogController\ & if not exist LogController\ exit 1
	cd LogController\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\LogController\LogController.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-LogController-LogController-pro-distclean: FORCE
	@if not exist LogController\ mkdir LogController\ & if not exist LogController\ exit 1
	cd LogController\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\LogController\LogController.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-LogController-LogController-pro-install_subtargets: FORCE
	@if not exist LogController\ mkdir LogController\ & if not exist LogController\ exit 1
	cd LogController\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\LogController\LogController.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-LogController-LogController-pro-uninstall_subtargets: FORCE
	@if not exist LogController\ mkdir LogController\ & if not exist LogController\ exit 1
	cd LogController\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\LogController\LogController.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-WeightModbus-qmake_all:  FORCE
	@if not exist WeightModbus\ mkdir WeightModbus\ & if not exist WeightModbus\ exit 1
	cd WeightModbus\ && $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\WeightModbus\WeightModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd WeightModbus\ && $(MAKE) -f Makefile qmake_all
sub-WeightModbus: FORCE
	@if not exist WeightModbus\ mkdir WeightModbus\ & if not exist WeightModbus\ exit 1
	cd WeightModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\WeightModbus\WeightModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-WeightModbus-make_first: FORCE
	@if not exist WeightModbus\ mkdir WeightModbus\ & if not exist WeightModbus\ exit 1
	cd WeightModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\WeightModbus\WeightModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-WeightModbus-all: FORCE
	@if not exist WeightModbus\ mkdir WeightModbus\ & if not exist WeightModbus\ exit 1
	cd WeightModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\WeightModbus\WeightModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-WeightModbus-clean: FORCE
	@if not exist WeightModbus\ mkdir WeightModbus\ & if not exist WeightModbus\ exit 1
	cd WeightModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\WeightModbus\WeightModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-WeightModbus-distclean: FORCE
	@if not exist WeightModbus\ mkdir WeightModbus\ & if not exist WeightModbus\ exit 1
	cd WeightModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\WeightModbus\WeightModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-WeightModbus-install_subtargets: FORCE
	@if not exist WeightModbus\ mkdir WeightModbus\ & if not exist WeightModbus\ exit 1
	cd WeightModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\WeightModbus\WeightModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-WeightModbus-uninstall_subtargets: FORCE
	@if not exist WeightModbus\ mkdir WeightModbus\ & if not exist WeightModbus\ exit 1
	cd WeightModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\WeightModbus\WeightModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-ZBY_MQ-ZBY_MQ-pro-qmake_all:  FORCE
	@if not exist ZBY_MQ\ mkdir ZBY_MQ\ & if not exist ZBY_MQ\ exit 1
	cd ZBY_MQ\ && $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\ZBY_MQ\ZBY_MQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd ZBY_MQ\ && $(MAKE) -f Makefile qmake_all
sub-ZBY_MQ-ZBY_MQ-pro: FORCE
	@if not exist ZBY_MQ\ mkdir ZBY_MQ\ & if not exist ZBY_MQ\ exit 1
	cd ZBY_MQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\ZBY_MQ\ZBY_MQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-ZBY_MQ-ZBY_MQ-pro-make_first: FORCE
	@if not exist ZBY_MQ\ mkdir ZBY_MQ\ & if not exist ZBY_MQ\ exit 1
	cd ZBY_MQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\ZBY_MQ\ZBY_MQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-ZBY_MQ-ZBY_MQ-pro-all: FORCE
	@if not exist ZBY_MQ\ mkdir ZBY_MQ\ & if not exist ZBY_MQ\ exit 1
	cd ZBY_MQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\ZBY_MQ\ZBY_MQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-ZBY_MQ-ZBY_MQ-pro-clean: FORCE
	@if not exist ZBY_MQ\ mkdir ZBY_MQ\ & if not exist ZBY_MQ\ exit 1
	cd ZBY_MQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\ZBY_MQ\ZBY_MQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-ZBY_MQ-ZBY_MQ-pro-distclean: FORCE
	@if not exist ZBY_MQ\ mkdir ZBY_MQ\ & if not exist ZBY_MQ\ exit 1
	cd ZBY_MQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\ZBY_MQ\ZBY_MQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-ZBY_MQ-ZBY_MQ-pro-install_subtargets: FORCE
	@if not exist ZBY_MQ\ mkdir ZBY_MQ\ & if not exist ZBY_MQ\ exit 1
	cd ZBY_MQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\ZBY_MQ\ZBY_MQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-ZBY_MQ-ZBY_MQ-pro-uninstall_subtargets: FORCE
	@if not exist ZBY_MQ\ mkdir ZBY_MQ\ & if not exist ZBY_MQ\ exit 1
	cd ZBY_MQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\ZBY_MQ\ZBY_MQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall

Makefile: ZBY_MQQ.pro C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/win32-g++/qmake.conf C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/spec_pre.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/qdevice.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/device_config.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/common/sanitize.conf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/common/gcc-base.conf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/common/g++-base.conf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/common/angle.conf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/common/windows-vulkan.conf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/common/g++-win32.conf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/qconfig.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3drender.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axbase.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axserver.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_charts.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_charts_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_datavisualization.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_dbus.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_designer.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_help.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_help_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_location.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_location_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_networkauth.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_nfc.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_positioning.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_purchasing.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qml.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quick.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_repparser.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_script.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_script_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_scripttools.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_scxml.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_sensors.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_serialport.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_uitools.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_websockets.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_winextras.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/qt_functions.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/qt_config.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/win32-g++/qmake.conf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/exclusive_builds.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/toolchain.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/default_pre.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/win32/default_pre.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/resolve_config.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/default_post.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/resources.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/qtquickcompiler.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/precompile_header.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/warn_on.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/qmake_use.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/file_copies.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/win32/windows.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/testcase_targets.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/exceptions.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/yacc.prf \
		C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/lex.prf \
		ZBY_MQQ.pro
	$(QMAKE) -o Makefile ZBY_MQQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/spec_pre.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/qdevice.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/device_config.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/common/sanitize.conf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/common/gcc-base.conf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/common/g++-base.conf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/common/angle.conf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/common/windows-vulkan.conf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/common/g++-win32.conf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/qconfig.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3drender.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axbase.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axserver.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_charts.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_charts_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_core.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_core_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_datavisualization.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_dbus.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_designer.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_gui.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_help.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_help_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_location.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_location_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_network.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_network_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_networkauth.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_networkauth_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_nfc.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_opengl.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_positioning.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_purchasing.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_purchasing_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qml.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quick.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_repparser.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_script.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_script_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_scripttools.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_scripttools_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_scxml.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_sensors.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_serialport.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_sql.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_svg.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_testlib.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_uitools.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_websockets.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_widgets.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_winextras.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_xml.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/qt_functions.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/qt_config.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/win32-g++/qmake.conf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/spec_post.prf:
.qmake.stash:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/exclusive_builds.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/toolchain.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/default_pre.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/win32/default_pre.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/resolve_config.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/exclusive_builds_post.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/default_post.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/resources.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/qtquickcompiler.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/precompile_header.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/warn_on.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/qmake_use.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/file_copies.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/win32/windows.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/testcase_targets.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/exceptions.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/yacc.prf:
C:/Qt/Qt5.12.9/5.12.9/mingw73_64/mkspecs/features/lex.prf:
ZBY_MQQ.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ZBY_MQQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler"

qmake_all: sub-DataInterPort-qmake_all sub-DataInterSerailPort-qmake_all sub-DataInterModbus-qmake_all sub-DataInterRabbitMQ-qmake_all sub-DataInterTcp-qmake_all sub-DataInterchange-qmake_all sub-LogController-LogController-pro-qmake_all sub-WeightModbus-qmake_all sub-ZBY_MQ-ZBY_MQ-pro-qmake_all FORCE

make_first: sub-DataInterPort-make_first sub-DataInterSerailPort-make_first sub-DataInterModbus-make_first sub-DataInterRabbitMQ-make_first sub-DataInterTcp-make_first sub-DataInterchange-make_first sub-LogController-LogController-pro-make_first sub-WeightModbus-make_first sub-ZBY_MQ-ZBY_MQ-pro-make_first  FORCE
all: sub-DataInterPort-all sub-DataInterSerailPort-all sub-DataInterModbus-all sub-DataInterRabbitMQ-all sub-DataInterTcp-all sub-DataInterchange-all sub-LogController-LogController-pro-all sub-WeightModbus-all sub-ZBY_MQ-ZBY_MQ-pro-all  FORCE
clean: sub-DataInterPort-clean sub-DataInterSerailPort-clean sub-DataInterModbus-clean sub-DataInterRabbitMQ-clean sub-DataInterTcp-clean sub-DataInterchange-clean sub-LogController-LogController-pro-clean sub-WeightModbus-clean sub-ZBY_MQ-ZBY_MQ-pro-clean  FORCE
distclean: sub-DataInterPort-distclean sub-DataInterSerailPort-distclean sub-DataInterModbus-distclean sub-DataInterRabbitMQ-distclean sub-DataInterTcp-distclean sub-DataInterchange-distclean sub-LogController-LogController-pro-distclean sub-WeightModbus-distclean sub-ZBY_MQ-ZBY_MQ-pro-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-DataInterPort-install_subtargets sub-DataInterSerailPort-install_subtargets sub-DataInterModbus-install_subtargets sub-DataInterRabbitMQ-install_subtargets sub-DataInterTcp-install_subtargets sub-DataInterchange-install_subtargets sub-LogController-LogController-pro-install_subtargets sub-WeightModbus-install_subtargets sub-ZBY_MQ-ZBY_MQ-pro-install_subtargets FORCE
uninstall_subtargets: sub-DataInterPort-uninstall_subtargets sub-DataInterSerailPort-uninstall_subtargets sub-DataInterModbus-uninstall_subtargets sub-DataInterRabbitMQ-uninstall_subtargets sub-DataInterTcp-uninstall_subtargets sub-DataInterchange-uninstall_subtargets sub-LogController-LogController-pro-uninstall_subtargets sub-WeightModbus-uninstall_subtargets sub-ZBY_MQ-ZBY_MQ-pro-uninstall_subtargets FORCE

sub-DataInterPort-debug:
	@if not exist DataInterPort\ mkdir DataInterPort\ & if not exist DataInterPort\ exit 1
	cd DataInterPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterPort\DataInterPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-DataInterSerailPort-debug:
	@if not exist DataInterSerailPort\ mkdir DataInterSerailPort\ & if not exist DataInterSerailPort\ exit 1
	cd DataInterSerailPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterSerailPort\DataInterSerailPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-DataInterModbus-debug:
	@if not exist DataInterModbus\ mkdir DataInterModbus\ & if not exist DataInterModbus\ exit 1
	cd DataInterModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterModbus\DataInterModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-DataInterRabbitMQ-debug:
	@if not exist DataInterRabbitMQ\ mkdir DataInterRabbitMQ\ & if not exist DataInterRabbitMQ\ exit 1
	cd DataInterRabbitMQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterRabbitMQ\DataInterRabbitMQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-DataInterTcp-debug:
	@if not exist DataInterTcp\ mkdir DataInterTcp\ & if not exist DataInterTcp\ exit 1
	cd DataInterTcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterTcp\DataInterTcp.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-DataInterchange-debug:
	@if not exist DataInterchange\ mkdir DataInterchange\ & if not exist DataInterchange\ exit 1
	cd DataInterchange\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterchange\DataInterchange.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-LogController-LogController-pro-debug:
	@if not exist LogController\ mkdir LogController\ & if not exist LogController\ exit 1
	cd LogController\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\LogController\LogController.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-WeightModbus-debug:
	@if not exist WeightModbus\ mkdir WeightModbus\ & if not exist WeightModbus\ exit 1
	cd WeightModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\WeightModbus\WeightModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-ZBY_MQ-ZBY_MQ-pro-debug:
	@if not exist ZBY_MQ\ mkdir ZBY_MQ\ & if not exist ZBY_MQ\ exit 1
	cd ZBY_MQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\ZBY_MQ\ZBY_MQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
debug: sub-DataInterPort-debug sub-DataInterSerailPort-debug sub-DataInterModbus-debug sub-DataInterRabbitMQ-debug sub-DataInterTcp-debug sub-DataInterchange-debug sub-LogController-LogController-pro-debug sub-WeightModbus-debug sub-ZBY_MQ-ZBY_MQ-pro-debug

sub-DataInterPort-release:
	@if not exist DataInterPort\ mkdir DataInterPort\ & if not exist DataInterPort\ exit 1
	cd DataInterPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterPort\DataInterPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-DataInterSerailPort-release:
	@if not exist DataInterSerailPort\ mkdir DataInterSerailPort\ & if not exist DataInterSerailPort\ exit 1
	cd DataInterSerailPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterSerailPort\DataInterSerailPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-DataInterModbus-release:
	@if not exist DataInterModbus\ mkdir DataInterModbus\ & if not exist DataInterModbus\ exit 1
	cd DataInterModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterModbus\DataInterModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-DataInterRabbitMQ-release:
	@if not exist DataInterRabbitMQ\ mkdir DataInterRabbitMQ\ & if not exist DataInterRabbitMQ\ exit 1
	cd DataInterRabbitMQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterRabbitMQ\DataInterRabbitMQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-DataInterTcp-release:
	@if not exist DataInterTcp\ mkdir DataInterTcp\ & if not exist DataInterTcp\ exit 1
	cd DataInterTcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterTcp\DataInterTcp.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-DataInterchange-release:
	@if not exist DataInterchange\ mkdir DataInterchange\ & if not exist DataInterchange\ exit 1
	cd DataInterchange\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterchange\DataInterchange.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-LogController-LogController-pro-release:
	@if not exist LogController\ mkdir LogController\ & if not exist LogController\ exit 1
	cd LogController\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\LogController\LogController.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-WeightModbus-release:
	@if not exist WeightModbus\ mkdir WeightModbus\ & if not exist WeightModbus\ exit 1
	cd WeightModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\WeightModbus\WeightModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-ZBY_MQ-ZBY_MQ-pro-release:
	@if not exist ZBY_MQ\ mkdir ZBY_MQ\ & if not exist ZBY_MQ\ exit 1
	cd ZBY_MQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\ZBY_MQ\ZBY_MQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
release: sub-DataInterPort-release sub-DataInterSerailPort-release sub-DataInterModbus-release sub-DataInterRabbitMQ-release sub-DataInterTcp-release sub-DataInterchange-release sub-LogController-LogController-pro-release sub-WeightModbus-release sub-ZBY_MQ-ZBY_MQ-pro-release

sub-DataInterPort-check:
	@if not exist DataInterPort\ mkdir DataInterPort\ & if not exist DataInterPort\ exit 1
	cd DataInterPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterPort\DataInterPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-DataInterSerailPort-check:
	@if not exist DataInterSerailPort\ mkdir DataInterSerailPort\ & if not exist DataInterSerailPort\ exit 1
	cd DataInterSerailPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterSerailPort\DataInterSerailPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-DataInterModbus-check:
	@if not exist DataInterModbus\ mkdir DataInterModbus\ & if not exist DataInterModbus\ exit 1
	cd DataInterModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterModbus\DataInterModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-DataInterRabbitMQ-check:
	@if not exist DataInterRabbitMQ\ mkdir DataInterRabbitMQ\ & if not exist DataInterRabbitMQ\ exit 1
	cd DataInterRabbitMQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterRabbitMQ\DataInterRabbitMQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-DataInterTcp-check:
	@if not exist DataInterTcp\ mkdir DataInterTcp\ & if not exist DataInterTcp\ exit 1
	cd DataInterTcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterTcp\DataInterTcp.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-DataInterchange-check:
	@if not exist DataInterchange\ mkdir DataInterchange\ & if not exist DataInterchange\ exit 1
	cd DataInterchange\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterchange\DataInterchange.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-LogController-LogController-pro-check:
	@if not exist LogController\ mkdir LogController\ & if not exist LogController\ exit 1
	cd LogController\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\LogController\LogController.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-WeightModbus-check:
	@if not exist WeightModbus\ mkdir WeightModbus\ & if not exist WeightModbus\ exit 1
	cd WeightModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\WeightModbus\WeightModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-ZBY_MQ-ZBY_MQ-pro-check:
	@if not exist ZBY_MQ\ mkdir ZBY_MQ\ & if not exist ZBY_MQ\ exit 1
	cd ZBY_MQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\ZBY_MQ\ZBY_MQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
check: sub-DataInterPort-check sub-DataInterSerailPort-check sub-DataInterModbus-check sub-DataInterRabbitMQ-check sub-DataInterTcp-check sub-DataInterchange-check sub-LogController-LogController-pro-check sub-WeightModbus-check sub-ZBY_MQ-ZBY_MQ-pro-check

sub-DataInterPort-benchmark:
	@if not exist DataInterPort\ mkdir DataInterPort\ & if not exist DataInterPort\ exit 1
	cd DataInterPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterPort\DataInterPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-DataInterSerailPort-benchmark:
	@if not exist DataInterSerailPort\ mkdir DataInterSerailPort\ & if not exist DataInterSerailPort\ exit 1
	cd DataInterSerailPort\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterSerailPort\DataInterSerailPort.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-DataInterModbus-benchmark:
	@if not exist DataInterModbus\ mkdir DataInterModbus\ & if not exist DataInterModbus\ exit 1
	cd DataInterModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterModbus\DataInterModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-DataInterRabbitMQ-benchmark:
	@if not exist DataInterRabbitMQ\ mkdir DataInterRabbitMQ\ & if not exist DataInterRabbitMQ\ exit 1
	cd DataInterRabbitMQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterRabbitMQ\DataInterRabbitMQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-DataInterTcp-benchmark:
	@if not exist DataInterTcp\ mkdir DataInterTcp\ & if not exist DataInterTcp\ exit 1
	cd DataInterTcp\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterTcp\DataInterTcp.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-DataInterchange-benchmark:
	@if not exist DataInterchange\ mkdir DataInterchange\ & if not exist DataInterchange\ exit 1
	cd DataInterchange\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\DataInterchange\DataInterchange.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-LogController-LogController-pro-benchmark:
	@if not exist LogController\ mkdir LogController\ & if not exist LogController\ exit 1
	cd LogController\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\LogController\LogController.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-WeightModbus-benchmark:
	@if not exist WeightModbus\ mkdir WeightModbus\ & if not exist WeightModbus\ exit 1
	cd WeightModbus\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\WeightModbus\WeightModbus.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-ZBY_MQ-ZBY_MQ-pro-benchmark:
	@if not exist ZBY_MQ\ mkdir ZBY_MQ\ & if not exist ZBY_MQ\ exit 1
	cd ZBY_MQ\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cc\Documents\Qt\ZBY_MQQ\ZBY_MQ\ZBY_MQ.pro -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-DataInterPort-benchmark sub-DataInterSerailPort-benchmark sub-DataInterModbus-benchmark sub-DataInterRabbitMQ-benchmark sub-DataInterTcp-benchmark sub-DataInterchange-benchmark sub-LogController-LogController-pro-benchmark sub-WeightModbus-benchmark sub-ZBY_MQ-ZBY_MQ-pro-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

